version: '3.2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_joomla
      - MARIADB_DATABASE=bitnami_joomla
    volumes:
       - type: volumes
         source: example
         target: /nfs
         volume:
            nocopy: true
  joomla:
    image: docker.io/bitnami/joomla:4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - JOOMLA_DATABASE_HOST=mariadb
      - JOOMLA_DATABASE_PORT_NUMBER=3306
      - JOOMLA_DATABASE_USER=bn_joomla
      - JOOMLA_DATABASE_NAME=bitnami_joomla
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

    volumes:
       - type: volumes
         source: example
         target: /nfs
         volume:
            nocopy: true

    depends_on:
      - mariadb

volumes:
  example:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.225.100,nolock,soft,rw"
      device: ":/volumes"
